version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: sudo pip install pipenv
      - run: pipenv install 
      - run: python -m unittest discover -p "Test_server*.py"
      - run: pipenv run pytest

workflows:
  main:
    jobs:
      - build-and-test
